HPCToolkit/hpctoolkit

- src/tool/hpcrun/ompt/ompt-interface.c
- src/tool/hpcrun/ompt/ompt.h
Add device interfaces and modify `ompt.h`. Apart from copying a new version of `ompt.h` to the directory, I found some things were missing in the codes. 
1. I modify `ompt_data_none` and `ompt_device_time_none` according to the new standard.
2. I add `ompt_thread_unknown` into `ompt_thread_type_t` according to the new standard.
> Add ompt device interfaces

- src/tool/hpcrun/sample-sources/perf/linux_perf.c
files opened for measurement with perf_events were leaked for threads. this code closes the leaked files.
> fix perf fd leak for threads.

- src/tool/hpcrun/cct/cct.c
- src/tool/hpcrun/cct/cct.h
- src/tool/hpcrun/cct/cct_bundle.c
- src/tool/hpcrun/main.c
- src/tool/hpcrun/ompt/ompt-callstack.c
- src/tool/hpcrun/ompt/ompt-callstack.h
- src/tool/hpcrun/ompt/ompt-defer.c
- src/tool/hpcrun/ompt/ompt-defer.h
- src/tool/hpcrun/ompt/ompt-interface.c
- src/tool/hpcrun/ompt/ompt-interface.h
- src/tool/hpcrun/ompt/ompt-region.c
- src/tool/hpcrun/ompt/ompt-task.c
- src/tool/hpcrun/ompt/ompt-thread.c
- src/tool/hpcrun/ompt/ompt-thread.h
- src/tool/hpcrun/ompt/ompt.h
- src/tool/hpcrun/sample_event.c
- src/tool/hpcrun/thread_data.h
Unwinding and collecting region call path is postponed until the end of region and happens only if any thread from team took a sample in that region.
> defer collecting region context

- doc/man/hpcproftt.tex
- src/tool/hpcproftt/Args.cpp
- src/tool/hpcproftt/Args.hpp
- src/tool/hpcproftt/Makefile.am
- src/tool/hpcproftt/Makefile.in
- src/tool/hpcproftt/hpcproftt.in
- src/tool/hpcproftt/main.cpp
- remove (unavailable) capabilities and options for anything other than dumping hpcrun files
- fix help message and man page
- move hpcproftt from bin directory to libexec/hpctoolkit by adjusting Makefile.am and hpcproftt.in
> hpcproftt is now a debugging tool only

- src/lib/analysis/CallPath-CudaCFG.cpp
- src/lib/banal/Struct.cpp
- src/lib/banal/cuda/CFGParser.cpp
- src/lib/banal/cuda/CFGParser.hpp
- src/lib/banal/cuda/CudaCFGFactory.cpp
- src/lib/banal/cuda/DotCFG.hpp
- src/tool/hpcrun/cct/cct.c
Now it works for a simple sample, but I still need to do the following things.
> Fix cfg parser for CUDA-9.2 nvdisasm changes

- src/lib/banal/Struct-Inline.hpp
- src/lib/banal/Struct.cpp
If L1 is an irreducible loop and L2 is an irreducible subloop and L1
and L2 have the same file and line attribution, then merge L2 into L1.
It's likely there is really only one loop in the source code.
This only applies to irreducible loops.  Natural (reducible) loops are
assumed to be correct.
> Merge irreducible loops.

- src/tool/hpcrun/gpu/gpu-activity-process.c
- src/tool/hpcrun/gpu/nvidia/cupti-activity-translate.c
1. It is safer to have a separate routine to handle memcpy2.
2. In some cases, if we leave the system to figure out a dtoh or a htod copy, the api callback itself does not specify the copy direction. Therefore by default we assign a <gpu copy> placeholder to these apis, such as `cuMemcpy`.
> Fix unassociated memcpy cct nodes

- src/lib/prof/CallPath-Profile.cpp
- src/tool/hpcrun/gpu/gpu-activity-process.c
- src/tool/hpcrun/gpu/gpu-metrics.c
- src/tool/hpcrun/gpu/gpu-metrics.h
- src/tool/hpcrun/gpu/nvidia/cupti-activity-translate.c
- src/tool/hpcrun/metrics.c
- src/tool/hpcrun/metrics.h
- src/tool/hpcrun/sample-sources/perf/linux_perf.c
- src/tool/hpcrun/sample-sources/perf/perfmon-util.c
- src/tool/hpcrun/sample-sources/perf/perfmon-util.h
The current hpcrun is already equipped with metric description, but it doesn't gather description from the sample-source. Hence, the content of the description is not used in hpcprof.
This patch includes:
- hpcrun: gathering metric description from perf_events sample-source.
- hpcrun: writing the description into hpcrun file
- hpcprof: exporting it to experiment.xml
Caveat: due to XML limitation, a metric description cannot include special charaters (need to convert to escape sequence).
> Exporting metric description into the database

- src/tool/hpcrun/gpu/gpu-metrics.h
The CMEM stall metric order is also adjusted according to `CUpti_ActivityPCSamplingStallReason`.
> Add missing gpu stall metrics

- src/tool/hpcrun/os/linux/dylib.c
we observed Linux reporting a name for the VDSO shared object.
it is the empty string on other platforms. avoid trying to
compute function bounds for vdso using a bogus file name.
> fix handling of vdso on arm

- configure
- configure.ac
- src/include/hpctoolkit-config.h.in
- src/tool/hpcfnbounds/Makefile.am
- src/tool/hpcfnbounds/Makefile.in
- src/tool/hpcfnbounds/hpcfnbounds.in
- src/tool/hpcfnbounds/main.cpp
- src/tool/hpcrun/scripts/hpcrun.in
support in Symtab.
1. configure tests if libsymtabAPI.so is compiled with openmp.
2. Makefile adds -fopenmp as needed.
3. hpcrun and hpcfnbounds support a '-js num' option to specify the
number of openmp threads for symtab in fnbounds (default 1).
4. rip out the option processing in the fnbounds launch script and
handle all options in the binary.  we haven't used this and it hasn't
worked right for years.
To use threads in hpcfnbounds, use a recent dyninst pre-10.2.0 from
master and export HPCFNBOUNDS_NUM_THREADS=num, or else use
'hpcrun -js num ...'.  OMP_NUM_THREADS applies to the application.
Although this commit supports threads in fnbounds, the latest Symtab
will use threads whether we support it or not.  The real purpose is to
prevent fnbounds from consuming every available thread …
> Adapt fnbounds to the upcoming Dyninst 10.2.0 release with openmp

- doc/www/software.html
'spack-issues.html' was removed in a recent merge.
> Fix a regression in doc/www/software.html.  It looks like the link to

- src/tool/hpcrun/sample-sources/perf/event_custom.h
- src/tool/hpcrun/sample-sources/perf/kernel_blocking.c
- src/tool/hpcrun/sample-sources/perf/linux_perf.c
Quick fix for issue #189 where profiling with -e BLOCKTIME causes segmentation fault in some cases, and memory corruption (but doesn't crash) in other cases.
Current solution: All linux_perf's custom-based events should be based on perf_event metric kind. Otherwise linux perf_event manager doesn't know how many metrics (or events) are there.
Long term solution: Linux perf_event custom-based events should be ideally more independent (ideally it should be a plugin).
> hpcrun: fix issue #189 (BLOCKTIME event crashes)

- src/tool/hpcrun/sample-sources/cuda.c
- src/tool/hpcrun/sample-sources/generic.c
- src/tool/hpcrun/sample-sources/gpu_blame.c
- src/tool/hpcrun/sample-sources/mpi.c
- src/tool/hpcrun/sample-sources/papi-c.c
- src/tool/hpcrun/sample-sources/papi.c
- src/tool/hpcrun/sample-sources/tst.c
- src/tool/hpcrun/sample-sources/upc.c
`hpcrun/metrics.h` declares `kind_info_t *` as the first arg.
```
int hpcrun_set_new_metric_info_and_period(kind_info_t *kind, const char* name,
MetricFlags_ValFmt_t valFmt, size_t period, 
metric_desc_properties_t prop);
```
But there are files such as  `cuda.c`, `generic.c`, `papi.c`, and `tst.c` that use it without the kind pointer.
Besides, `hpcrun_close_kind` is not called in some places after `hpcrun_metrics_new_kind` is used.
> Fix incorrect use of hpcrun_set_new_metric_info_and_period and missing hpcrun_close_kind

- src/lib/prof/CallPath-Profile.cpp
**Symptom**: hpcprof generates the same flat ID (or struct ID) for the same inlined macro (single alien) from different contexts, which confuses the viewer when creating the flat view.
**Root cause**: Before writing experiment.xml, hpcprof removes redundant procedures by ensuring the tuple `<Load_module, Filename, Procedure, line_number>` is unique. However, for inline macros, we shouldn't remove redundancy. Or perhaps we should add `<Load_module, Filename, Procedure, line_number, "parent_id">` to be unique.
**Solution**: add "`parent_id`" in the tuple to make sure single alien is unique based on its context.
> Fix issue 68 (incorrect struct ID for single aliens)

- configure
- configure.ac
This one burned me while trying to minimize my Boost footprint. Without this, `./configure` will just happily let some (very long) link commands fail mysteriously.
> Add a configure-time requirement on Boost system + graph.

- src/tool/hpcrun/main.c
- src/tool/hpcrun/main.h
- src/tool/hpcrun/sample-sources/itimer.c
- src/tool/hpcrun/sample-sources/papi-c.c
- src/tool/hpcrun/sample-sources/papi.c
- src/tool/hpcrun/sample-sources/perf/linux_perf.c
- src/tool/hpcrun/sample-sources/upc.c
Use a thread local counter to suppress samples during dlopen and dlclose
> Suppress samples during dlopen and dlclose

- src/lib/isa-lean/power/instruction-set.h
- src/tool/hpcrun/unwind/ppc64/ppc64-unwind-interval.c
Add support for recognizing interior tail calls when creating PPC64 unwind recipes.
@mwkrentel @mxz297 please review the code and test further. the memstress test now has no errant unwinds. 
quicksilver works too, though I now notice 2 unknown procedures. these may have been a consequence of keren's recent change (but not this commit).
> Ppc64 unwinder tail call

- src/tool/hpcrun/sample-sources/perf/kernel_blocking.c
Minor update:
- Rename CS into CNTXT_SWTCH
- Hide context switches metric by default
> Fix issue #238: rename context switches event

- src/tool/hpcrun/gpu/nvidia/cupti-api.c
- src/tool/hpcrun/gpu/nvidia/cupti-api.h
- src/tool/hpcrun/sample-sources/nvidia.c
- src/tool/hpcrun/sample-sources/nvidia.h
Use `finalize_event_list` to register Cupti activities without knowing CUDA context. 
Only PC sampling is registered when a context is created because pc sampling configuration needs to know which context the kernel belongs to. 
Tests for Laghos, Quicksolver, and simpleCooperativeGroups have been done. 
@mxz297 , can you double check this commit?
> Cupti buffer fix

- doc/texinfo/spack-issues.texi
- doc/www/spack-issues.html
- spack/spack-issues.txt
Intel moved their repo for TBB, thus invalidating all of the
spack sha256 checksums.
> Add the intel-tbb checksums to the current spack issues page.

- doc/man/hpcprof.tex
- src/lib/analysis/ArgsHPCProf.cpp
- src/lib/analysis/ArgsHPCProf.hpp
- src/tool/hpcprof-mpi/main.cpp
- src/tool/hpcprof/Args.cpp
hpcprof at the moment doesn't support --metric-db, we should remove this option from the help (-h) and the man page.
> Remove --metric-db from hpcprof

- src/lib/prof/NameMappings.cpp
This is to help hpcviewer to distinguish between place folders and normal procedures. 
hpcviewer will add the name of the load module if a node doesn't have the source code. However,
if a node is a place holder, hpcviewer should not add the load module name (since the source code is not available).
> Add GPU and OMP place folders as "fake" procedures

- src/lib/analysis/CallPath-CudaCFG.cpp
- src/tool/hpcrun/cct/cct.c
- src/tool/hpcrun/cct/cct.h
- src/tool/hpcrun/cct/cct_bundle.c
- src/tool/hpcrun/gpu/gpu-activity-process.c
- src/tool/hpcrun/gpu/gpu-host-correlation-map.c
- src/tool/hpcrun/gpu/nvidia/cupti-api.c
- src/tool/hpcrun/main.c
- src/tool/hpcrun/threadmgr.c
1. If `-e nvidia` is used, we attribute kernel metrics to `<gpu kernel>` but not `<gpu trace>`. This is the simplest case.
2. If `-e nvidia -t` is used, we attribute kernel metrics to `<gpu kernel>`, and we pass a child of `<gpu kernel>` to tracing threads, which can help show specific function names in *hpctraceviewer*.
3. If `-e nvidia,pc` is used, we assign the first instruction of gpu kernels a pseudo sample, if needed, to avoid dividing zero in apportion. 
@jmellorcrummey , @laksono , I suggest test both quicksilver and laghos to verify the correctness of this commit.
> Merge <gpu-kernel> nodes

- src/tool/hpcrun/gpu/gpu-metrics.c
1. I believe `cct_metric_data_t.i` should be a `uint64_t` value.
2. The integer overflow error was found while profiling a single spec accel kernel that runs for 1 minute, collecting samples greater than *2^22*. When we do scaling at Line 275, *2^22 * 2^10 = 2^32*, causing an overflow.
> Fix integer overflow while collecting pc samples for a long running kernel

- src/tool/hpcrun/gpu/gpu-metrics.h
times had previously been updated to be computed in seconds, but the labels still said microseconds (us).
> correct labels of GPU synchronization metrics

- src/tool/hpcstruct/Makefile.am
- src/tool/hpcstruct/Makefile.in
- src/tool/hpcstruct/stringify.py
Needed to build on recent Debian, which has removed `python` in favor of the versioned dichotomy `python2` and `python3`.
Also fixes an issue where the build would fail strangely in compilation if Python wasn't available on the first `make` invocation.
> Use and prefer versioned Python interpreters for stringify.py.

- configure
- configure.ac
- src/tool/hpcrun/Makefile.am
- src/tool/hpcrun/Makefile.in
- src/tool/hpcrun/gpu/amd/rocm-binary-processing.c
- src/tool/hpcrun/gpu/amd/rocm-binary-processing.h
- src/tool/hpcrun/gpu/amd/rocm-debug-api.c
- src/tool/hpcrun/gpu/amd/rocm-debug-api.h
- src/tool/hpcrun/gpu/amd/roctracer-activity-translate.c
- src/tool/hpcrun/gpu/amd/roctracer-api.c
- src/tool/hpcrun/gpu/gpu-activity-process.c
- src/tool/hpcrun/module-ignore-map.c
- src/tool/hpcrun/sample-sources/amd.c
1. Update the use of roctracer to reflect API changes from rocm 2.x
2. Use AMD debug library to query binary URI and extract AMD GPU binary
3. Ignore monitoring threads created by AMD libraries
> AMD GPU support with rocm 3.7

- src/tool/hpcrun/Makefile.am
- src/tool/hpcrun/Makefile.in
- src/tool/hpcrun/gpu/level0/level0-api.c
- src/tool/hpcrun/gpu/level0/level0-api.h
- src/tool/hpcrun/gpu/level0/level0-command-list-context-map.c
- src/tool/hpcrun/gpu/level0/level0-command-list-context-map.h
- src/tool/hpcrun/gpu/level0/level0-command-list-map.c
- src/tool/hpcrun/gpu/level0/level0-command-process.c
- src/tool/hpcrun/sample-sources/level0.c
- src/tool/hpcrun/sample-sources/level0.h
This PR refactors Level0 support to work with Intel OneAPI Beta 9 or newer. Older versions of OneAPI is no longer supported. 
We also used function override to intercept Level0's public API as previous tracing support in Level0 is now marked as experimental and will be removed in the future.
I have rebased this PR upon the latest LD_AUDIT commits and tested it with DPC++ samples.
> L0 refactor

- src/tool/hpcrun/gpu/gpu-trace.c
- src/tool/hpcrun/main.c
- src/tool/hpcrun/threadmgr.c
- src/tool/hpcrun/threadmgr.h
Ensure that cpu_thread never becomes a prefix of gpu thread.
> Demand new thread data for gpu_trace_stream

- src/tool/hpcrun/cct2metrics.c
- src/tool/hpcrun/metrics.c
- src/tool/hpcrun/metrics.h
The existing hpctoolkit **doesn't** have the bug I mentioned in the meeting last week. Originally, I thought hpcrun incorrectly attributes metrics if there are multiple metrics kind because the allocation interface `hpcrun_reify_metric_set` does not consider the case when different `metric_id`s are passed for the same `cct_id`. 
However, the bug actually was resolved by myself back to 2019 in this commit:
https://github.com/HPCToolkit/hpctoolkit/commit/0a4707c8be275fd5427269c2e89c4c1501921932
This commit guarantees the correctness of metrics attribution by lazy initialization of all the metric kinds. The following code change propose a solution to early initialize metric kinds directly in `hpcrun_reify_metric_set`. Hope this change could make the code clearer. 
If needed, I can remove the …
> Enhance hpcrun_reify_metric_set to eagerly allocate metrics_kind

- src/tool/hpcrun/gpu/amd/rocm-binary-processing.c
- src/tool/hpcrun/gpu/amd/rocm-debug-api.c
- src/tool/hpcrun/gpu/amd/roctracer-activity-translate.c
- src/tool/hpcrun/gpu/amd/roctracer-api.c
- src/tool/hpcrun/module-ignore-map.c
- src/tool/hpcrun/scripts/hpcrun.in
1. Support extraction of multiple GPU binaries
2. Suppress empty trace line caused by AMD debug api
3. Disable Rocm deferred loading in hpcrun script to ensure capturing all GPU binaries.
@jmellorcrummey I rebased on develop today (so, Jonathon's ld_audit fix is included) and tested it with PeleC on Tulip. Everything looks good.
> AMD GPU support improvement

- src/include/gpu-binary.h
- src/lib/prof-lean/crypto-hash.c
- src/lib/prof-lean/crypto-hash.h
- src/tool/hpcrun/gpu/amd/rocm-binary-processing.c
- src/tool/hpcrun/gpu/nvidia/cupti-api.c
- src/tool/hpcstruct/Args.cpp
- src/tool/hpcstruct/Makefile.am
- src/tool/hpcstruct/Makefile.in
- src/tool/hpcstruct/gpubin-analysis.txt
- src/tool/hpcstruct/main.cpp
- now record AMD and NVIDIA GPU binaries in a directory "gpubins" with the suffix "gpubin"
- adjust hpcstruct to analyze contents of gpubins directory
> unify support for recording and analyzing GPU binaries

- src/tool/hpcrun/audit/auditor.c
The got table of one library and code from another library can be
in the same page. Therefore, we need to add exec permission as well.
> Fix memory protection problem caused by overwriting got table.

- src/tool/hpcrun/main.c
In practice this generates a warning during compilation and an error during the link phase of `hpclink`.
> Don't try to init the auditor in the static case.

- src/tool/hpcrun/Makefile.am
- src/tool/hpcrun/Makefile.in
- src/tool/hpcrun/gpu/level0/level0-api.c
- src/tool/hpcrun/gpu/opencl/opencl-api-wrappers.c
- src/tool/hpcrun/gpu/opencl/opencl-api.c
- src/tool/hpcrun/scripts/hpcrun.in
Move OpenCL wrappers to libhpcrun_opencl.so. This also includes fixes to Level0 support for a bug that I accidentally encountered. I also compile the code with both `--with-level0` and `--with-opencl` at configure time. The same build works for dpcpp code using either level0 backend or opencl backend, meaning `SYCL_BE=PI_LEVEL_ZERO hpcrun -e gpu=level0 ...` and `SYCL_BE=PI_OPENCL hpcrun -e gpu=opencl ...` both works.
@jmellorcrummey I don't have an environment to test GTPin support ready. Can you test this branch with GTPin?
> Opencl wrappers

- src/tool/hpcrun/gpu/gpu-metrics.c
- src/tool/hpcrun/gpu/gpu-metrics.h
A metric that adds the time spent by all GPU operations.
> GPUOP metric

- src/tool/hpcrun/scripts/hpcrun.in
Current develop branch will fail to find a library from roctracer due to a typo in the hpcrun script.
> Fix typo in hpcrun script for setting roctracer path

- src/tool/hpcrun/loadmap.c
fix #321. in short, unmap notification to the unwind recipe map occurred too late - after a shared library's representation as a dso_info object in the loadmap was cleared. remedy this by performing unmap notifications before discarding the dso_info for a shared library in the loadmap.
> Fix issue 321 - problem with dynamic library unmap notification 

- src/tool/hpcrun/audit/audit-api.h
- src/tool/hpcrun/audit/auditor.c
Test code:
```
#--- Makefile
all: main libfoo.so libbar.so
clean:
rm -f main libfoo.so libbar.so
libbar.so: bar.c
gcc -o $@ $^ -shared
libfoo.so: foo.c libbar.so
gcc -o $@ -shared -Wl,-rpath=`realpath .` -L. $< -lbar
main: main.c libbar.so
gcc -o $@ -Wl,-rpath=`realpath .` -L. $< -lbar -ldl
//--- main.c
#include <dlfcn.h>
extern void bar();
int main() {
bar();
void* h = dlopen("libfoo.so", RTLD_LAZY);
void (*foo)() = dlsym(h, "foo");
foo();
dlclose(h);
}
//--- foo.c
extern void bar();
void foo() {
bar();
for(int i = 0; i < 1<<28; i++) bar();
}
//--- bar.c
void bar() {}
```
Output:
```console
$ \time ./main
0.46user 0.00system 0:00.46elapsed 99%CPU (0avgtext+0avgdata 1188maxresident)k
0inputs+0outputs (0major+87minor)pagefaults 0swaps
$ \time hpcrun -e REALTIME@0 ./main  # Before
22.56user …
```
> Fix PLT optimization for dlopen'd libraries

- src/tool/hpcrun/gpu/gpu-activity-process.c
Surprisingly, it reduces the execution monitoring overhead by 36%, and the end to end overhead by 60%.
@dejangrubisic Can you help me verify the benefits on gpu.cs and llnl.cs? I only ran it on gpu.cs. Just use `hpcrun -e gpu=nvidia`, and https://github.com/HPCToolkit/hpctoolkit-tutorial-examples/tree/master/examples/gpu/laghos
> Avoid creating the background tracing thread when -t is not specified

- src/tool/hpcrun/control-knob.c
- src/tool/hpcrun/gpu/gpu-operation-multiplexer.c
- src/tool/hpcrun/gpu/gpu-trace-demultiplexer.c
- src/tool/hpcrun/gpu/gpu-trace.c
- src/tool/hpcrun/gpu/gpu-trace.h
- src/tool/hpcrun/main.c
- src/tool/hpcrun/sample_sources_registered.c
- src/tool/hpcrun/utilities/hpcrun-nanotime.c
- src/tool/hpcrun/utilities/hpcrun-nanotime.h
Adaptation to Keren's change of finalizer function, and deleting gpu_operation_channel_set_await as unnecessery
> introduced how arg in device_finalizer_fn

- src/tool/hpcrun/gpu/amd/rocm-binary-processing.c
- src/tool/hpcrun/main.c
- src/tool/hpcrun/scripts/hpcrun.in
1. The rocm support code will directly return when finding out that the GPU binary exists, which will skip the steps to fill in data structures representing the list of GPU binaries. The fix is to just skip writing to disk but not the steps of filling the needed data structures.
2. Currently, running `hpcrun -L` will create an unwanted measurement directory. A full solution requires more thoughts on the ordering of the startup sequences. This PR includes a temporary solution that simply skips operations related creating measurement directory.
> Fixes regarding measurement directory

- src/tool/hpcrun/gpu/amd/roctracer-activity-translate.c
- src/tool/hpcrun/gpu/gpu-trace.c
- src/tool/hpcrun/thread_data.c
- src/tool/hpcrun/thread_data.h
1. Do not record time stamps of HIP API executed on the host side. Record the time stamps of actual GPU operations from the GPU.
2. Fix GPU tracing, which requires matched time stamps for GPU operations and "no activity". This is a problem for all GPU platforms.
> ROCm support fix and GPU tracing fix

- src/lib/banal/gpu/DotCFG.hpp
- src/lib/banal/gpu/GPUBlock.cpp
- src/lib/banal/gpu/ReadCudaCFG.cpp
- src/lib/banal/gpu/ReadIntelCFG.cpp
Use arch flag to determine the entry id of a GPU instruction; If using dyninst 10.2, intel GPU instruction is not supported
> GPU CFG construction fix for dyninst@10.2

- src/tool/hpcrun/control-knob.c
- src/tool/hpcrun/gpu/gpu-operation-multiplexer.c
The bug was created when we want to register a control knob that is already registered. Instead of just changing the value, I was mistakenly setting next pointers, which should be done only when adding a control knob the first time in the list.
> Fixed issues of uninitialized gpu_trace_finished and control_knob.c circular list

- src/tool/hpcrun/control-knob.c
- src/tool/hpcrun/gpu/gpu-trace-channel.c
- src/tool/hpcrun/gpu/gpu-trace-item.c
- src/tool/hpcrun/gpu/gpu-trace-item.h
- src/tool/hpcrun/gpu/gpu-trace.c
- src/tool/hpcrun/gpu/gpu-trace.h
Based on the latest experiment we(John and I) conclude that one tracing thread is capable of dealing with 256 GPU streams.
Based on Oracle PE, we put gpu_trace_cct_no_activity out of the trace-consuming loop and get some performance.
> STREAMS_PER_TRACING_THREAD default set to 256 and gpu_trace_cct_no_activity optimization

- src/tool/hpcrun/main.c
- src/tool/hpcrun/scripts/hpcrun.in
Add a command-line option to shutdown the hpcfnbounds after the app started and shared library processed. Now default is only shutting down at the end of execution.
> Fnbounds shutdown

- src/lib/prof/NameMappings.cpp
- src/tool/hpcstruct/pmake.txt
- fix placeholders that are not matched because function names in stripped binaries (libmonitor and libhpcrun) get their load module added to them
- skip hpcstruct analysis of libhpcrun, libmonitor, libpfm, libcuda, libcupti, libxed ...
> fine tune strategy of applying hpcstruct to whole measurement directories

- src/lib/banal/Struct.cpp
Functions from stripped binaries have functions names "outline" as a prefix and have redundant load module in their names. Such names are misleading. Use "unknown procedure @address [load module]" for their name.
> Fix naming for stripped functions

- src/tool/hpcrun/fnbounds/fnbounds_client.c
An attempt to fix the `wait()` issue reported by @martyitz, and an alternative approach to fixing the large memory space slowdowns reported and partially resolved by @Lucindaaaa in #420.
Background: The Fnbounds server process is spawned as a child of the application process through a direct call to `clone()`. After the merge of #420, the Fnbounds server stays around by default throughout the entire application execution. @martyitz discovered that this causes issues with applications using `wait()` since the Fnbounds server is now (from the application's perspective) a rogue mystery child process that doesn't seem to die.
There are two commits here, the first attempts to fix the `wait()` issue by spawning the Fnbounds process as a grandchild, removing its "child" status and thus making it …
> Spawn Fnbounds as a Grandchild

- src/tool/hpcstruct/pmake.txt
The new version of the Struct Makefile (for processing an entire measurements directory) do not work out-of-the-box on my Debian rig, since in Debian `/bin/sh` is not bash but a minimal POSIX shell called [dash](https://manpages.debian.org/unstable/dash/dash.1.en.html).
This patch removes the reliance on two bash-isms that aren't present in all POSIX-compliant shells:
- In bash, `&> file` or `>& file` can be used to redirect both standard output and error to the same file, being equivalent to `> file 2>&1`. The Makefile only uses this to redirect to `/dev/null`, so the constructs are replaced with `>&- 2>&-` which closes standard output and error for the same effect.
- Bash supports a `pushd` builtin to manipulate the "directory stack," a mechanism for saving working directories over the …
> Fix a couple of POSIX shell compatibility bugs in the hpcstruct Makefile

- src/lib/prof-lean/hpcrun-fmt.h
- src/tool/hpcrun/gpu/gpu-trace.c
- src/tool/hpcrun/main.c
- src/tool/hpcrun/sample-sources/amd.c
- src/tool/hpcrun/sample-sources/common.h
- src/tool/hpcrun/sample-sources/cuda.c
- src/tool/hpcrun/sample-sources/itimer.c
- src/tool/hpcrun/sample-sources/level0.c
- src/tool/hpcrun/sample-sources/nvidia.c
- src/tool/hpcrun/sample-sources/opencl.c
- src/tool/hpcrun/sample-sources/papi-c.c
- src/tool/hpcrun/sample-sources/perf/linux_perf.c
- src/tool/hpcrun/sample_event.c
- src/tool/hpcrun/threadmgr.c
- src/tool/hpcrun/trace.c
- src/tool/hpcrun/trace.h
1. Add <no activity> to CPU traces when there is a long gap without any sample
2. Only do cpu tracing when a time based metric is specified, such as cycles, cputime, and realtime.
3. Print an error message when -t is specified but no suitable tracing metric is given
4. fix itimer event's handling of sampling frequency
5. Cut GPU traces size by half
> Various fixes related to CPU tracing

- src/lib/prof/NameMappings.cpp
The cause of the bug is because hpcprof generated the 'f' attribute of <Partial call paths> to "1" (folder node) instead of "4" (top down folder).
By setting the value to "4" fixes this problem.
> Fix hpcviewer.e4 bug #108 (partial call path in flat view)00

- src/lib/prof-lean/Makefile.am
- src/lib/prof-lean/Makefile.in
- src/lib/prof-lean/cpuset_hwthreads.c
- src/lib/prof-lean/cpuset_hwthreads.h
- src/tool/hpcstruct/Args.cpp
- src/tool/hpcstruct/main.cpp
- src/tool/hpcstruct/pmake.txt
- src/tool/hpcstruct/usage.txt
* overhaul hpcstruct to be parallel by default
- add parallelism by default:
default concurrency: cpuset size /2
default parallelism: min(16, cpuset size/2)
- have job control throttle parallelism
- error message when output file for directory
- rewrite usage message
- migrage usage message to usage.txt
- add path to hpcstruct to makefile
- bulletproof parallel makefile for exceptional cases
no measurement files
* update hpcstruct help message
* fix typo
> overhaul hpcstruct to be parallel by default (#445)

- src/tool/hpcprof/main.cpp
With the help of @Jokeren , this fixes the bug that PC sampling requiring -t. I tested this PR with quicksilver on ufront. I compared the a few calling contexts with/without -t and the they look the same. The database with pc sampling without -t still have GPU call frames.
I am not certain about the side effect of this change related to CPU profiling.
> Fix the need of -t to enable GPU CFG construction

- src/tool/hpcrun/fnbounds/fnbounds_client.c
Fixes #455, ping @jmellorcrummey and @mwkrentel. IMO 2.24 is old enough we could get away with just dropping support, if not though this PR provides a hacky fix.
There is a bug in older Glibc (https://sourceware.org/bugzilla/show_bug.cgi?id=18862) where using `CLONE_VM` instead of `CLONE_THREAD` causes the Glibc wrapper to reset its internal pthread state in the parent process. This wreaks havoc with all things pthread, but most noticably it stops the `pthread_kill` in libmonitor's shootdown from functioning (and libmonitor doesn't pay attention enough to the returned error codes).
As a sort of hack, it turns out the reset happens after the body passed to `clone`, so killing the child via a signal instead of returning dodges the issue. At least, it seems to work on 2.17.
This also adds an …
> Avoid hanging at exit when using CLONE_VM on Glibc <2.24

- src/lib/support-lean/OSUtil.c
- src/lib/support-lean/OSUtil.h
Doesn't fix any known issues, but may prevent very hard-to-debug issues in the future.
There was a comment in this region that claimed some versions of RHEL 6.x had issues with gethostid() triggering a SIGFPE, the previous implementation would catch and gracefully absorb the signal. There is no clean and contained way to do this in thread-safe manner, so this version doesn't do so (and thus is much simpler).
---
Targeting `master` since this patch is not specific to anything in `develop`.
Ping @mwkrentel as the author of the previous version of this function (and the RHEL 6.x comment).
> Fixup OSUtil_hostid for thread-safety and unsigned return

- src/tool/hpcrun/gpu/amd/roctracer-api.c
- src/tool/hpcrun/gpu/gpu-trace.c
- src/tool/hpcrun/gpu/nvidia/cupti-api.c
- src/tool/hpcrun/main.c
- src/tool/hpcrun/thread_data.c
- src/tool/hpcrun/thread_data.h
This patch introduces **hpcrun_thread_init_mem_pool_once** at the beginning of each thread created from the monitoring tool (hpcrun or vendor-api) to process tracing/profiling data. This is necessary because these threads need to have initialized thread-data structure, since they create channels and other things with td data structure.
I added this function at the beginning of **cupti/rocm_buffer_completion_callback** and **gpu_trace_record**. I can see that there are pthread_create calls for:
- stream_data_collecting,
- finalize_all_thread_data,
- gpu_operation_record 
Should I put **hpcrun_thread_init_mem_pool_once** for them too?
Let me know if this patch solves the problem with cuda versions, we talked on the meeting.
> Patch memory pool create

- src/tool/hpcrun/main.c
Patch memory pool create required one more change from Keren:
https://github.com/HPCToolkit/hpctoolkit/pull/473#issuecomment-958084480
Which is returning MONITOR_IGNORE_NEW_THREAD from monitor_thread_pre_create. This feature goes together with libmonitor ignore-from-pre-create branch that needs to be merged.
https://github.com/HPCToolkit/libmonitor/pull/2
> Returning MONITOR_IGNORE_NEW_THREAD from monitor_thread_pre_create

- .e4s/e4s.yaml
The E4S metadata is part of E4S policy. My understanding is that it requires a yaml file in `.e4s` directory.
The content of the yaml is an adaptation from https://github.com/E4S-Project/E4S-Documenter/blob/master/data/hpctoolkit/e4s.yaml where the `MemberProduct` field is set to `True` (instead of `False`).
The metadata is not well documented and strangely, even E4S team doesn't know what this field means.
> Add the E4S metadata

- src/tool/hpcrun/sample-sources/amd.c
use a device flush finalizer to  ensure that roctracer activity
tracing is shut down and roctracer activity traces are
flushed.
this must be done before a device shutdown finalizer calls
gpu_trace_fini. otherwise, some trace records may not be flushed
to disk.
the handshake between gpu_trace_fini and tracing threads REQUIRES
that tracing has been shut down and traces are flushed from
roctracer before gpu_trace_fini sets stop_trace_flag.
> ensure roctracer traces are written to disk

- src/lib/prof-lean/hpcrun-fmt.h
- src/lib/prof/CallPath-Profile.cpp
- src/tool/hpcrun/loadmap.c
- src/tool/hpcrun/loadmap.h
- src/tool/hpcrun/write_data.c
binaries are often loaded into an address space that do
not end up on a call path; such binaries don't need binary
analysis. mark load modules that we queried with
hpcrun_loadModule_findByAddr as needing binary analysis.
> adjust loadmap to note which load modules need analysis

- src/tool/hpcrun/sample-sources/nvidia.c
before this commit:
1) a device flush finalizer flushes cupti activity traces.
2) the last registered device shutdown finalizer calls
gpu_trace_fini
3) the first registered  device shutdown finalizer shuts
down cuda activity tracing and flushes any remaining
traces
issues: (3) shuts down and flushes cuda traces after gpu
tracing has been finalized. (1) and (3) both flush
after this commit
1) a device flush finalizer shuts down cuda activity tracing
and flushes any remaining traces
2) a device shutdown finalizer calls gpu_trace_fini
improvements: cuda activity tracing is disabled before a single
flush. a single flush occurs before gpu_trace_fini, as it must.
> cleanup finalization of CUDA traces

- src/tool/hpcrun/fnbounds/fnbounds_static.c
- src/tool/hpcrun/sample-sources/ss-list.h
- have hpcrun mark a static binary for binary analysis by hpcstruct
- don't require AMD GPU sample source for static binaries (the code is not even built)
> Hpcrun static

- src/tool/hpcrun/device-finalizers.c
- src/tool/hpcrun/device-finalizers.h
- src/tool/hpcrun/sample-sources/nvidia.c
- ensure that device finalizers are called in the order that they are registered
- register cupti_device_flush as a device_flush finalizer
- regster cupti_device_shutdown and then gpu_trace_fini as device_shutdown finalizers
> fix cupti thread and process finalizer order

- src/tool/hpcrun/sample-sources/perf/linux_perf.c
- src/tool/hpcrun/sample-sources/perf/perfmon-util.c
Instead of having a footnote to warn of probably unprofilable events, it's better to show the note in the beginning.
This fix will show this message in the beginning of perf sample source when using -L flag:
(*) Denotes the counter may not be profilable.
...
Minor update:
- remove warning
- remove unnecessary info from libpfm4 about the number of events for each perf module. Users don't care.
> hpcrun: Add a "head note" for probably unprofilable events

- src/tool/hpcrun/sample-sources/level0.c
finalize level0 traces by calling gpu_trace_fini as last device finalizer when shutting down the process.
> finalize level0 traces

- src/tool/hpcrun/gpu/amd/roctracer-api.c
- src/tool/hpcrun/gpu/amd/roctracer-api.h
- src/tool/hpcrun/sample-sources/amd.c
- thread device finalizer flushes trace
- process device finalizer shuts down rocm measurement, flushes trace, then calls gpu_trace_fini
> roctracer support for fixing finalization

- src/lib/banal/gpu/DotCFG.hpp
Fix a cuda cfg parsing problem for CUDA >= 11.5: target labels are changed from .L_<number> to .L_x_<number>, so new code is added to extract name using the new pattern.
Interestingly, using cuda-11.6 collects 13% less samples than cuda-11.4 for quicksilver, but it has nothing to do with postmortem analysis. I confirmed this issue using hpctoolkit's log file.
> CUDA-11.6-fix

- src/tool/hpcrun/control-knob.c
An important fix on control knob: before this commit, external knobs using hpcrun -ck @name=@value does not work becaue only names in the default knobs are registers. Since iter = control_knob_name_lookup(name) is NULL if name is external (e.g., ones used by nvidia.c), their @values are not passed into hpcrun
> [New CUPTI] Control knob

- src/tool/hpcrun/threadmgr.c
- src/tool/hpcrun/threadmgr.h
Refine variable naming: 1. no_separator should be a bool instead of int. 2. Using \!no_separator does not make sense; it is more straightforward to name it add_separator
> [New CUPTI] threadmgr variable

- src/lib/profile/accumulators.cpp
- src/lib/profile/accumulators.hpp
- src/lib/profile/context.hpp
- src/lib/profile/pipeline.cpp
- src/lib/profile/pipeline.hpp
- src/lib/profile/sinks/packed.cpp
- src/lib/profile/sinks/sparsedb.cpp
- src/lib/profile/sinks/sparsedb.hpp
- src/lib/profile/sources/packed.cpp
- src/lib/profile/util/parallel_work.hpp
The next phase for #495 requires changes to the SparseDB, however the code is somewhat complicated and hard to read. With the exception of the first commit, this patch series attempts to incrementally massage it without changing the high-level algorithm, into something more readable, better contained and somewhat better documented.
The first commit fixes a bug where cct.db would be left unwritten with a single MPI rank. Most other commits (prefixed with "Cleanup:") are incremental changes that improve the SparseDB implementation without changing the top-level algorithm or the final output. The couple of remaining commits are improvements to the Prof2 core/utilities that assist in the cleanup.
> Cleanup SparseDB

- configure
- configure.ac
When compiling with `--with-spack`, if the Binutils it picks up was compiled with `~libiberty` (which is default), the build fails with the error:
```
In file included from demangle.c:59:
.../hpctoolkit/src/include/gnu_demangle.h:68:10: fatal error: libiberty/demangle.h: No such file or directory
68 | #include <libiberty/demangle.h>
|          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
This patch adds includes handling to the separated libiberty logic.
> Fix: Separate libiberty fails to compile

- src/tool/hpcrun/gpu/gpu-trace.c
- src/tool/hpcrun/thread_data.c
- src/tool/hpcrun/threadmgr.c
- src/tool/hpcrun/threadmgr.h
This PR fixes the problem of overwriting thread_data structure by setting mem_pool_initialized on right place.
> Fixing hpcrun_threadMgr_data_get problem

- src/tool/hpcrun/Makefile.am
- src/tool/hpcrun/Makefile.in
Fixes an issue where --enable-develop/debug didn't compile the auditor with debug flags, so debugging was more difficult than it should have been.
...But seriously, Autogoo is a mess, this sort of thing should be automatic.
> Apply CFLAGS to libhpcrun_{,fake_}audit.so

- src/lib/banal/Struct-Output.cpp
- src/lib/banal/Struct-Output.hpp
- src/lib/banal/Struct.cpp
format conversion (except index numbers and gaps) and can run in
parallel, and finalPrintProc() which runs serially and adds the index
numbers and writes to the struct file.
This allows the bulk of the format conversion to run in parallel and
dramatically reduces the "print engine spike" in hpcstruct.
> Split printProc() into: earlyFormatProc() which performs most of the

- src/tool/hpcrun/sample-sources/papi-c.c
Fix error below when there is a typo in the hpcrun metric name
```
symbol lookup error: libhpcrun.so: undefined symbol: is_event_to_exclude
```
> Remove undefined call

- src/tool/hpcrun/audit/auditor.c
- src/tool/hpcrun/main.c
have both the auditor and hpctoolkit ensure that auditor does not execute connect in forked child.
> don't connect to auditor in a forked child

- src/tool/hpcrun/messages/messages-sync.c
previously, the error message just indicated that a log close failed. the new error message indicates the name of the process and pid where the log closure failed. with that, one can look in the measurement data and see the short log.
note 1: the problem came up when using hpcrun to monitor bash with spack being set up in the .bashrc. python apparently forked. jonathon reports that python closes everything except standard file descriptors on fork, which closes our log file. on jlse, using hpcrun to monitor bash then reports that a particular python process got a cropped log file. this is much better than just reporting that something bad happened.
note 2: we can't call malloc or stdio functions here because we might be ending hpctoolkit because a user typed ^c in the middle of a memory …
> improve hpcrun error message for closed log file

- configure
- configure.ac
- src/tool/hpcrun/gpu/amd/rocprofiler-api.c
- support configure with /opt/rocm-5.0.0
- support component config with rocm pieces specified explicitly
- adjust paths to a few rocprofiler include files
- remove rocm debug API as a configure option
- avoid redundant include paths for /opt/rocm-5.0.0 configuration
> configure support for rocm 5

- src/tool/hpcrun/ompt/ompt-device.c
- src/tool/hpcrun/sample-sources/openmp-target.c
- for ompt target emi callbacks, values for *host_op_id weren't being computed by hpcrun
- remove unused variables in openmp-target sample source.
> fix ompt target issues

- src/tool/hpcstruct/SingleBin.cpp
- src/tool/hpcstruct/renamestruct.sh
- replace "@echo" with "echo" in renamestruct.sh script
(@echo is a make construct but not legal bash)
- fix monitor_execve failure warning when using hpcrun to measure
hpcstruct. the issue was that hpcrun was trying to exec
a script directly. instead of running the rename script
with command  "<path>/renamestruct.sh", run it with command
"/bin/sh <path>/renamestruct.sh". that way, /bin/sh can be
exec'ed. i think that if such an exec failed in the shell,
the shell probably figures out how to launch the command
by finding the "#!/bin/sh" in the first line of the shell
script.
> fix issues with renaming structure files in the cache

- Makefile.am
- Makefile.in
- configure
- configure.ac
- src/tool/hpcrun/Makefile.am
- src/tool/hpcrun/Makefile.in
libhpcrun.o.  This allows us to hide the xed symbols inside our
library in case the application also uses xed.
This now requires xed to be built statically (.a) with fPIC.
----------
@jmellorcrummey  This is the fix for the xed symbol clash.
Before merging into something, I want to test three things:
1. test on ppc and arm (me)
2. test on theta with static hpcprof-mpi (me)
3. verify that it actually does fix the xed clash with 2022.04.17 (johnmc)
> Rework how we handle xed to link xed directly into libhpcrun.so and

- src/tool/hpcrun/lush/lush.c
- src/tool/hpcrun/unwind/common/backtrace.c
- src/tool/hpcrun/unwind/common/libunw_intervals.c
- src/tool/hpcrun/unwind/common/libunw_intervals.h
- src/tool/hpcrun/unwind/common/unwind.h
- src/tool/hpcrun/unwind/generic-libunwind/libunw-unwind.c
- src/tool/hpcrun/unwind/ppc64/ppc64-unwind.c
- src/tool/hpcrun/unwind/x86-family/x86-unwind.c
When unwinding a stack frame, the PC in the resulting frame is a return address, rather
than a call address. If the compiler did not expect the call to return, the compiler may
pack instructions in a way such that the unwind recipe for the return address is not the
same as the call address.
This commit changes the semantic of hpcrun_unw_step to always result in a "caller" frame,
with an approximate call address of (return address - 1), instead of the "return" frame
returned previously. This simplifies the incomplete logic added in b99930f9b3d4bb3d9e384e9f91e212cc0df53d53
and extends it to apply to the generic libunwind and Power cases as well.
The x86 native unwinder is unchanged in this commit, it fails to unwind even in the
microtest case used to validate this patch.
Fixes #540
> Unwind callers not returns

- src/tool/hpcrun/Makefile.am
- src/tool/hpcrun/Makefile.in
- src/tool/hpcrun/gpu/instrumentation/gtpin-instrumentation.c
- src/tool/hpcrun/gpu/instrumentation/gtpin-interface.c
- src/tool/hpcrun/gpu/instrumentation/gtpin-knob.cpp
- src/tool/hpcrun/gpu/instrumentation/gtpin-knob.h
Intel's GT-Pin tool now only has a C++ API for certain functionality.  Setting GT-Pin control knobs is one of the features only available through C++. Create a separate C++ library for hpcrun to load that controls GT-Pin knobs.
> Add a C++ GT-Pin support library for use by hpcrun

- src/lib/banal/Struct-Output.cpp
- src/lib/banal/Struct-Output.hpp
- src/lib/banal/Struct.cpp
suppress generation of call site tags for CPU binaries.
First, nothing in hpctoolkit uses them so it is pointless to generate
them.
Second, hpcprof rejects any structure file with a <C> tag that
represents a call to an address not identified as a function in the
structure file. Some nested functions are not reported as functions,
so some structure files with <C> tags are rejected by hpcprof in
practice.
> hpcstruct: no <C> tags for CPU binaries

- src/tool/hpcstruct/main.cpp
- acknowledge that hpcstruct can take a directory as an argument and that any directory argument must be a hpctoolkit measurement directory
- make the form of error messages consistent with error messages from hpcprof
> improve hpcstruct error messages

- src/tool/hpcrun/gpu/level0/level0-data-node.c
make the level0 data node free list thread private to eliminate races between threads manipulating the list concurrently.
other alternatives:
- make it shared with locking
- have it use a high-performance threaded allocator
and no free list
> hpcrun: fix races for level0 data node free list

- src/tool/hpcrun/gpu/amd/roctracer-api.c
This fixes the symbol error for said procedure when running with `-gpu=amd`.
> Remove stray reference to ensure_kernel_ip_present() in amd/roctracer-api.c

- src/tool/hpcrun/gpu/amd/rocprofiler-api.c
- src/tool/hpcrun/gpu/amd/roctracer-api.c
- src/tool/hpcrun/gpu/gpu-operation-multiplexer.c
- src/tool/hpcrun/gpu/gpu-trace.c
- src/tool/hpcrun/gpu/instrumentation/gtpin-instrumentation.c
- src/tool/hpcrun/gpu/nvidia/cupti-api.c
- src/tool/hpcrun/gpu/opencl/opencl-api.c
- src/tool/hpcrun/sample_event.c
- src/tool/hpcrun/thread_data.h
- src/tool/hpcrun/threadmgr.c
Ideally, tool threads shouldn't be monitored. that is not true for OpenCL at present.
At a minimum:
- Don't assign an ID to a tool thread that conflicts with application thread 0
- Don't write profiles for tool thread
- Don't assemble traces for a tool thread
> hpcrun: distinguish tool threads with TOOL_THREAD_ID

- src/tool/hpcstruct/hpcstruct.in
- src/tool/hpcstruct/usage.txt
ensure that OpenMP workers have the same size stack as the main
thread by setting their stack size to "ulimit -s" kilobytes
> hpcstruct: set OMP_STACKSIZE

- src/lib/prof-lean/hpcrun-fmt.h
- src/lib/profile/sinks/hpctracedb2.cpp
- src/lib/profile/sources/hpcrun4.cpp
- src/lib/profile/sources/hpcrun4.hpp
- src/tool/hpcrun/gpu/amd/rocprofiler-api.c
- src/tool/hpcrun/gpu/amd/roctracer-api.c
- src/tool/hpcrun/gpu/gpu-operation-multiplexer.c
- src/tool/hpcrun/gpu/gpu-trace.c
- src/tool/hpcrun/gpu/instrumentation/gtpin-instrumentation.c
- src/tool/hpcrun/gpu/nvidia/cupti-api.c
- src/tool/hpcrun/gpu/opencl/opencl-api.c
- src/tool/hpcrun/main.c
- src/tool/hpcrun/sample-sources/gpu/stream-tracing.c
- src/tool/hpcrun/thread_data.c
- src/tool/hpcrun/thread_data.h
- src/tool/hpcrun/threadmgr.c
- src/tool/hpcrun/threadmgr.h
- src/tool/hpcrun/trace.c
- src/tool/hpcrun/trace.h
CPU traces are composed of a series of "samples" taken from every running thread. In contrast, GPU traces are (currently) composed only of top-level operations such as `<gpu copy>` or kernel launches. This PR better supports the latter case by marking such "call traces" and preventing deep lexical expansion (of inlined call chains) in Prof2 for these traces.
Fixes #619.
> Support call traces

- src/tool/hpcrun/safe-sampling.h
- src/tool/hpcrun/unwind/common/uw_recipe_map.c
This was observed when trying to profile PeleC with AMD GPU on ufront.cs.
> Handle dlopen in threads without thread_data

- src/tool/hpcrun/gpu/amd/roctracer-api.c
AMD merged ACTIVITY_DOMAIN_HCC_OPS into ACTIVITY_DOMAIN_HIP_OPS.
Rather than eliminating ACTIVITY_DOMAIN_HCC_OPS, they wrote
#define ACTIVITY_DOMAIN_HCC_OPS ACTIVITY_DOMAIN_HIP_OPS
Thus, tracing both ACTIVITY_DOMAIN_HCC_OPS and
ACTIVITY_DOMAIN_HIP_OPS meant tracing ACTIVITY_DOMAIN_HIP_OPS
twice. This corrupts the heap inside roctracer.
Eliminate tracing for ACTIVITY_DOMAIN_HCC_OPS since we already
trace ACTIVITY_DOMAIN_HIP_OPS.
> Don't trace ACTIVITY_DOMAIN_HCC_OPS

- src/tool/hpcrun/gpu/amd/roctracer-api.c
Tested with rocm/5.2.0:
Need to enable ACTIVITY_DOMAIN_HIP_OPS to trace gpus
if this is disabled, no profiles in gpu kernels
> roctracer: enable ACTIVITY_DOMAIN_HIP_OPS
