src/tool/hpcrun/sample-sources/itimer.c

block timer signal even for thread-centric timers such as REALTIME
after turning it off. REALTIME was observed to be delivered after it's
timer was turned off.
delete a thread's timer when finalizing a thread to avoid leaking timers.

adjust handling for timers to ensure that no samples follow finalization

---

src/tool/hpcrun/sample-sources/perf/linux_perf.c
src/tool/hpcrun/trace.c

Merged some commits from ompt-tr4 branch containing fixes in traces (min time) and linux perf_events (shootdown)

Bug fixes in hpcrun

---

src/lib/prof-lean/cskiplist.c
src/lib/prof-lean/cskiplist.h
src/tool/hpcrun/sample-sources/perf/linux_perf.c
src/tool/hpcrun/trace.c

Merge from commit in ompt-tr4
2a4d60f :  end sampling with perf carefully
09660fe : hpcrun: record trace min time at first sample instead of at open
d83b77e : fix cskiplist and improve debugging support

Fixes for perf_events, trace and cskiplist

---

configure
src/tool/hpcrun/Makefile.am
src/tool/hpcrun/Makefile.in
src/tool/hpcrun/ompt/ompt-interface.c

Merge one commit not fetched to local

Ompt device cfg master

---

src/tool/hpcrun/ompt/ompt-callstack.c
src/tool/hpcrun/ompt/ompt-interface.c
src/tool/hpcrun/ompt/ompt-region.c

changes that enable callstack eliding to work with LOMP

Openmp5 gpu lomp

---

src/tool/hpcrun/gpu/gpu-event-id-map.c

The `eventId` field is a little confusing.
https://docs.nvidia.com/cupti/Cupti/annotated.html#structCUpti__ActivityCudaEvent
> uint32_t CUpti_ActivityCudaEvent::eventId
> A unique event ID to identify the event record.
> 
EventId is unique with regard to `cuEventCreate` but not 'cuEventRecord'. That is, when an event is created (cuEventCreate), it is assigned a unique id. When an event is pushed into a stream (cuEventRecord), it triggers the creation of a `CUpti__ActivityCudaEvent` record. If the event is pushed again, CUPTI API creates another `CUpti__ActivityCudaEvent` record with the same event id but a different correlationId.

Handle duplicated event id

---

src/tool/hpcrun/unwind/common/backtrace.c

Fix unprotected stack unwind trampoline code

---

src/tool/hpcrun/gpu/amd/roctracer-api.c
src/tool/hpcrun/gpu/amd/roctracer-api.h
src/tool/hpcrun/main.c
src/tool/hpcrun/sample-sources/amd.c
src/tool/hpcrun/sample-sources/blame-shift/blame-sample-source.h
src/tool/hpcrun/sample-sources/cuda.c
src/tool/hpcrun/sample-sources/ga.c
src/tool/hpcrun/sample-sources/generic.c
src/tool/hpcrun/sample-sources/gpu_blame.c
src/tool/hpcrun/sample-sources/idle.c
src/tool/hpcrun/sample-sources/io.c
src/tool/hpcrun/sample-sources/itimer.c
src/tool/hpcrun/sample-sources/memleak.c
src/tool/hpcrun/sample-sources/mpi.c
src/tool/hpcrun/sample-sources/none.c
src/tool/hpcrun/sample-sources/nvidia.c
src/tool/hpcrun/sample-sources/papi-c.c
src/tool/hpcrun/sample-sources/perf/linux_perf.c
src/tool/hpcrun/sample-sources/pthread-blame.c
src/tool/hpcrun/sample-sources/retcnt.c
src/tool/hpcrun/sample-sources/sample_source_obj.h
src/tool/hpcrun/sample-sources/ss_obj.h
src/tool/hpcrun/sample-sources/sync.c
src/tool/hpcrun/sample-sources/tst.c
src/tool/hpcrun/sample-sources/upc.c
src/tool/hpcrun/sample_sources_all.c
src/tool/hpcrun/sample_sources_all.h

1. Implement finalize_event_list to load libroctracer.so
2. set environment variable to work around AMD toolchain hanging with interrupts
3. Update code to use roctracer C interface

Amd gpu fixes

---

src/tool/hpcrun/fnbounds/fnbounds_client.c

Fixes a number of issues with `pthread_atfork` handlers. Probably only works on Linux.

Use clone() rather than fork() for spawning the hpcfnbounds process.

---

src/lib/analysis/CallPath.cpp
src/lib/analysis/Util.cpp
src/lib/prof/CallPath-Profile.cpp

Procedure name normalization for VDSO and unknown procedures

---

src/lib/analysis/Util.cpp

@blue42u Can you test this one more time?

Only add virtual address and load module to <unknown procedure>

---

src/tool/hpcrun/gpu/gpu-metrics.h
src/tool/hpcrun/unwind/common/libunw_intervals.c

Fixes a number of the Deepwave partials.
Also sync with `master`.

[pytorch] Let Libunwind do its thing

---

src/tool/hpcrun/gpu/nvidia/cupti-api.c

@jmellorcrummey If you wouldn't mind merging this quick.
Syncs with master, and changes out the problematic calls for a slightly less problematic call.

[pytorch] Turing Partial Fix

---

src/lib/binutils/RelocateCubin.cpp
src/lib/prof-lean/Makefile.am
src/lib/prof-lean/Makefile.in
src/lib/prof-lean/elf-helper.c
src/lib/prof-lean/elf-helper.h
src/tool/hpcrun/gpu/nvidia/cubin-symbols.c

Involved cases:
1. Extended section name string table index
2.Section index for each symbol

Handling extended numbering for ELF

---

src/tool/hpcrun/gpu/gpu-activity-process.c
src/tool/hpcrun/gpu/nvidia/cupti-api.c

- use a separate gpu kernel placeholder for tracing
necessary to show proper routine in trace for kernels with
multiple functions
- move kernel metrics from trace placeholder to kernel
placeholder
- elide trace placeholder in hpcviewer

adjustments to tracing to fix trace and profile of quicksilver

---

src/lib/isa-lean/power/instruction-set.h
src/tool/hpcrun/unwind/ppc64/ppc64-unwind-interval.c
src/tool/hpcrun/unwind/ppc64/ppc64-unwind.c

these changes improve support for idioms found in applications and libraries compiled by IBM XL compilers.

Adjustments to power unwinder to dramatically reduce partial call paths 

---

src/tool/hpcrun/sample-sources/opencl.c

Opencl fix for writing trace files.

opencl writing trace files enabled

---

src/tool/hpcrun/gpu/nvidia/cupti-api.c
src/tool/hpcrun/sample-sources/nvidia.c

Also adds a big comment with a description of the issue.
@jmellorcrummey Edit the comments as necessary if I missed something.

CUPTI fork() Handling Hotfix

---

doc/man/hpcrun.tex
src/tool/hpcrun/fnbounds/fnbounds_client.c
src/tool/hpcrun/main.c
src/tool/hpcrun/messages/messages.flag-defns
src/tool/hpcrun/scripts/hpcrun.in
src/tool/hpcrun/unwind/common/backtrace.c
src/tool/hpcrun/unwind/common/backtrace.h
src/tool/hpcrun/unwind/common/uw_recipe_map.c
src/tool/hpcrun/unwind/generic-libunwind/libunw-unwind.c
src/tool/hpcrun/unwind/ppc64/ppc64-unwind.c
src/tool/hpcrun/unwind/x86-family/x86-unwind.c

I think I've done the right git-stuff, and would like to see the pull into master before the release.
Thanks,
Marty

No unwind implementation

---

src/tool/hpcrun/audit/auditor.c

If libhpcrun initializes early, the auditor may witness its initialization and assume its prepared to receive notifications before it actually is (via a recursive initialization attempt).
This patch instead assumes that the mainlib will notify the auditor when it is prepared, and thus delays notifications until that point.
The middling `connecting` state is still needed to prevent (some) recursive initializations.
Fixes issues with PeleC and other applications that spawn threads in their init constructors.
@mxz297

Delay auditor notifications until libhpcrun is certainly ready

---

src/tool/hpcrun/audit/auditor.c
src/tool/hpcrun/scripts/hpcrun.in

Tested on gpu (standard x86 PLT), ufront (security extension x86 PLT), and llnl (power).

PLT call performance fix

---

src/tool/hpcrun/audit/auditor.c
src/tool/hpcrun/audit/fake-auditor.c

fix issues with vdso entry presented to hpctoolkit
- fix start address
- fix end address
- fix dpi_addr

adjust vdso handling in auditor.c

---

src/tool/hpcrun/gpu/amd/rocm-debug-api.c
src/tool/hpcrun/gpu/amd/roctracer-api.c

Fix compile time and runtime problems with rocm-3.10

Work with rocm-3.10

---

src/tool/hpcrun/Makefile.am
src/tool/hpcrun/Makefile.in
src/tool/hpcrun/gpu/amd/rocm-debug-api.c
src/tool/hpcrun/gpu/level0/level0-api-wrappers.c
src/tool/hpcrun/gpu/level0/level0-api.c
src/tool/hpcrun/gpu/level0/level0-api.h
src/tool/hpcrun/gpu/nvidia/cupti-api.c
src/tool/hpcrun/sample-sources/level0.c
src/tool/hpcrun/scripts/hpcrun.in
src/tool/hpcrun/utilities/bgq-cnk/Makefile.in
src/tool/hpcserver/Makefile.in
src/tool/hpcserver/mpi/Makefile.in
src/tool/hpcstruct/Makefile.in
src/tool/hpctracedump/Makefile.in
src/tool/misc/Makefile.in
src/tool/xprof/Makefile.in

Isolate level 0 public API wrappers to a separate libhpcrun_level0.so. Also fixed regression on rocm and nvidia platforms.

Level0 wrappers

---

src/tool/hpcrun/gpu/gpu-activity-process.c
src/tool/hpcrun/gpu/gpu-activity.h
src/tool/hpcrun/gpu/gpu-metrics.c
src/tool/hpcrun/gpu/gpu-metrics.h
src/tool/hpcrun/gpu/nvidia/cupti-activity-translate.c

Nothing special, just collect the number of block per GPU kernel instance to check if all sms are used.

Gpu blocks

---

src/tool/hpcrun/audit/auditor.c

Opens permissions on the entire GOT table instead of just the first few pages, since it appears that Glibc will lock it down early in the LD_AUDIT case (probably since LD_AUDIT uses a shadow-GOT).
This version uses the GNU_RELRO program header(s) to determine where to adjust, under the assumption that if the binary has none the linker won't know what to lock down (and so won't).
This also cleans up the program header handling, under the assumption that the binaries are always the same architecture as the auditor. This assumption prevails in the rest of the auditor code, if it turns out to be false (multi-arch application) we can adjust more completely then.

Fix the PLT optimizations (part 2)

---

src/tool/hpcrun/fnbounds/fnbounds_client.c

As per the email thread, the changes in #423 added a bug on ARM where the grandchild would cause a bus error. Although I don't have an exact rationale why this would occur, separating the child and grandchild stacks seems to resolve the issue.

Hotfix the grandchild Fnbound spawn (fixes bus error on ARM)

---

src/lib/prof-lean/hpcrun-fmt.h
src/lib/prof/NameMappings.cpp
src/tool/hpcrun/fnbounds/fnbounds_client.c
src/tool/hpcrun/gpu/gpu-trace.c
src/tool/hpcrun/main.c
src/tool/hpcrun/sample-sources/amd.c
src/tool/hpcrun/sample-sources/common.h
src/tool/hpcrun/sample-sources/cuda.c
src/tool/hpcrun/sample-sources/itimer.c
src/tool/hpcrun/sample-sources/level0.c
src/tool/hpcrun/sample-sources/nvidia.c
src/tool/hpcrun/sample-sources/opencl.c
src/tool/hpcrun/sample-sources/papi-c.c
src/tool/hpcrun/sample-sources/perf/linux_perf.c
src/tool/hpcrun/sample_event.c
src/tool/hpcrun/threadmgr.c
src/tool/hpcrun/trace.c
src/tool/hpcrun/trace.h
src/tool/hpcstruct/pmake.txt

update with master

---

src/lib/prof-lean/Makefile.am
src/lib/prof-lean/Makefile.in
src/lib/prof-lean/cpuset_hwthreads.c
src/lib/prof-lean/cpuset_hwthreads.h
src/tool/hpcstruct/Args.cpp
src/tool/hpcstruct/main.cpp
src/tool/hpcstruct/pmake.txt
src/tool/hpcstruct/usage.txt

- add parallelism by default:
-- default concurrency: cpuset size /2
-- default parallelism: min(16, cpuset size/2)
- have job control throttle parallelism
- error message when output file for directory
- rewrite usage message
- migrage usage message to usage.txt
- add path to hpcstruct to makefile
- bulletproof parallel makefile for exceptional cases
-- no measurement files

overhaul hpcstruct to be parallel by default

---

src/lib/banal/Struct.cpp

Don't avoid all inline steps as in 2b6dda9a1a.  Instead, use the
inline step if it containes an exit cond at a deeper level.
For one example analyzing hpcstruct, this reduces the number of loops
at line 0 from 77 to 4 (not counting PLT examples).
Add extra debugging output for the file and line choices.

Rework the rules for how struct chooses the file/line for a loop.

---

src/tool/hpcrun/sample_event.c

at the end of an execution, a synchronous unwind to acquire a GPU API callpath was getting skipped, returning a NULL, which caused a SEGV. don't skip synchronous unwinds just because monitor_block_shootdown() returns a value that indicates a thread is already waiting at exit.

don't skip a synchronous unwind

---

src/lib/profile/accumulators.cpp
src/lib/profile/context.cpp
src/lib/profile/context.hpp

Take 2 at the redistribution factors for GPU calling context reconstruction. This version attempts to learn from the mistakes of the previous version. It shouldn't crash, but accuracy is untested.
The factors used for redistributing metric values among reconstructed GPU calling contexts are now the product of:
- [Interior factors](https://github.com/HPCToolkit/hpctoolkit/blob/4399cd703bf1726d37063cac7e557656cbb1be30/src/lib/profile/context.hpp#L341-L350), which distribute based on the call graph itself. The new algorithm considers all potential callers and distributes metric value if there are multiple callers based on the number of calls to the current function. This (should) give better results than the old algorithm, which considered possible callees instead (and thus would give bad …

Fix the GPU Context Reconstruction Factors (again)

---

doc/man/hpcviewer.tex
doc/www/download.html
doc/www/download.html.in

Minor updates:
- Fix and refine the man page for the viewer
- Update the download page to show the prior versions (2021.10 and 2021.05)

Update the man page of the viewer and its download page

---

src/tool/hpcrun/gpu/amd/rocm-debug-api.c
src/tool/hpcrun/gpu/amd/roctracer-api.c

we need to update to rocm 4.5 for testing on ufront and crusher

update to rocm 4.5

---

src/tool/hpcrun/files.c
src/tool/hpcrun/files.h
src/tool/hpcrun/fnbounds/fnbounds_client.c
src/tool/hpcrun/gpu/amd/rocm-binary-processing.c
src/tool/hpcrun/gpu/amd/rocprofiler-api.c
src/tool/hpcrun/gpu/amd/rocprofiler-api.h
src/tool/hpcrun/gpu/amd/roctracer-activity-translate.c
src/tool/hpcrun/gpu/gpu-activity-process.c
src/tool/hpcrun/gpu/gpu-metrics.c
src/tool/hpcrun/gpu/nvidia/cupti-activity-translate.c
src/tool/hpcrun/main.c
src/tool/hpcrun/write_data.c

fix issues that caused a large collection of compiler warnings

fix compiler warnings

---

src/tool/hpcrun/ompt/ompt-task.c

when a target nowait is executed outside an explicit parallel
region, it is nested only in the implicit (serialized) parallel
region surrounding the initial task. the implicit parallel
region does not get a parallel begin callback, so its
parallel_data is uninitialized. in this case, the nowait task
can't inherit its callpath from the enclosing parallel region
and it needs to unwind the call stack to determine its call path.

fix ompt support for target nowait

---

src/lib/profile/util/log.cpp
src/lib/profile/util/log.hpp
src/tool/hpcprof/args.cpp
src/tool/hpcstruct/MeasDir.cpp
src/tool/hpcstruct/Structure-Cache.cpp
src/tool/hpcstruct/pmake.txt

hpcprof's default output directory is now an INFO message instead of a warning.
hpcstruct's NOTE messages are now INFO messages

refine messages from hpcprof and hpcstruct

---

src/tool/hpcprof/args.cpp

Enhancing Jonathon's improvements.

hpcprof: refine messages about output database

---

src/tool/hpcrun/unwind/x86-family/x86-unwind.c

Add unwinding support for Intel Control-flow Enforcement Technology (CET), which may mark a branch target with the 'endbr64' instruction.
With Intel's compilers, we sometimes encounter routines marked with endbr64 that have symbols at an address 4 bytes less than where DWARF FDEs begin for the function. This disrupts their lookup with libunwind. For that reason, we consider adjusting the starting address of a function. If we fail to build unwind intervals for a routine from FDEs, then if
the routine begins with an 'endbr64' instruction, adjust the start of the routine to after the instruction and try building unwind intervals again.

hpcrun: add unwinding support for Intel CET

---

Makefile.am
Makefile.in

`Makefile.in` has been regenerated too.

Fix broken build from license rename

---

src/tool/hpcrun/gpu/amd/roctracer-activity-translate.c

ensure devices have separate trace lines by propagating roctracer device_id and queue_id into hpctoolkit's context_id and stream_id.

improve roctracer trace lines: use device+queue
